-- MySQL Script generated by MySQL Workbench
-- 07/23/14 18:07:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema session_lesson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `session_lesson` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `session_lesson` ;

-- -----------------------------------------------------
-- Table `session_lesson`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `session_lesson`.`users` (
  `login` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `year_of_birth` INT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
